# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='titolo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='basicapp.Titolo'),
            preserve_default=False,
        ),
    ]
