# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-09 08:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180105_0823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='authon',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='authon',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 9, 8, 10, 33, 761000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 9, 8, 10, 33, 761000, tzinfo=utc)),
        ),
    ]
